name: remote ssh command
on:
  release:
    types: [ published ]
#  push:
#    branches: [ actions-dev ]

jobs:
  build:
    name: copy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          source: "./docker-compose.yml, ./Dockerfile"
          target: "~/.deploy/${{ github.event.repository.name }}/"